// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zphcywrizplursqeuzyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwaGN5d3JpenBsdXJzcWV1enlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MTYyNzIsImV4cCI6MjA2ODQ5MjI3Mn0.71wmk_Ew2PjaNlw8jKSuspaspE0qtz1D9F1lELNUqcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});